#! /bin/sh

# echo $(dirname $(realpath $0))/aesdsocket

case $1 in
    start)
        echo "Starting aesdsocket"
        start-stop-daemon -S -n aesdsocket -a $(dirname $(realpath $0))/aesdsocket -- -d
        ;;
    stop)
        echo "Stopping aesdsocket"
        start-stop-daemon -K -n aesdsocket
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0